apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: EventRateLimit # protects against spaming events 
  configuration:
    apiVersion: eventratelimit.admission.k8s.io/v1alpha1
    kind: Configuration
    limits:
    - type: Server
      qps: 50 # limit of 50 events per second
      burst: 100 # allow short burst of 100 events
    - type: Namespace
      qps: 20 
      burst: 40