apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-demo
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: progrium/stress
        args: ["--cpu", "1"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.2"
          limits:
            memory: "256Mi"
            cpu: "0.5"
#kubectl --kubeconfig kube_config_cluster.yml apply -f stress-demo.yaml
